version: '3'

services:
  react-next-blog-sample:
    container_name: ts-react-next
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - NODE_DEV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
       - 3000:3000
       - 9005:9005
    tty: true
    stdin_open: true
